Add test case that exemplifies bug in --separate-chains for CIF input.

diff --git a/tests/test-cli.in b/tests/test-cli.in
--- a/tests/test-cli.in
+++ b/tests/test-cli.in
@@ -75,8 +75,19 @@ function assert_equal_total
 {
     tmp1=tmp/tmp1
     tmp2=tmp/tmp2
+
     eval $1 $2 | grep "Total" > $tmp1 2>/dev/null
+    if [[ $? -ne 0 ]]; then
+        echo Error: \"$1 $2\" fails
+        let errors=errors+1
+    fi
+
     eval $1 $3 | grep "Total" > $tmp2 2>/dev/null
+    if [[ $? -ne 0 ]]; then
+        echo Error: \"$1 $3\" fails
+        let errors=errors+1
+    fi
+
     diff $tmp1 $tmp2
     if [[ $? -ne 0 ]]; then
         echo Error: \"$1\" gives different results with arguments \"$2\" and \"$3\"
@@ -220,7 +231,7 @@ assert_equal_total "$cli" "$datadir/1d3z.pdb" "$datadir/1d3z.cif --cif"
 assert_equal_total "$cli" "$datadir/2jo4.pdb" "$datadir/2jo4.cif --cif"
 assert_equal_total "$cli" "$datadir/5hdn.pdb" "$datadir/5hdn.cif --cif"
 assert_equal_total "$cli" "$datadir/3bkr.pdb" "$datadir/3bkr.cif --cif"
-assert_equal_total "$cli" "$datadir/3gnn.pdb" "$datadir/3gnn.cif --cif"
+assert_equal_total "$cli -w" "$datadir/3gnn.pdb" "$datadir/3gnn.cif --cif"
 assert_equal_total "$cli --join-models" "$datadir/2jo4.pdb" "$datadir/2jo4.cif --cif"
 assert_equal_total "$cli --chain-groups AB+CD -S -n 10" "$datadir/2jo4.pdb" "$datadir/2jo4.cif --cif"
 
@@ -229,6 +240,8 @@ echo "== Testing --separate-chains and --separate-models output are equal betwee
 assert_equal_total "$cli --separate-chains -S -n 10" "$datadir/2jo4.pdb" "$datadir/2jo4.cif --cif"
 assert_equal_total "$cli --separate-chains -S -n 10" "$datadir/2isk.pdb" "$datadir/2isk.cif --cif"
 assert_equal_total "$cli --separate-chains -S -n 10" "$datadir/1sui.pdb" "$datadir/1sui.cif --cif"
+assert_equal_total "$cli --separate-chains -S -n 10" "$datadir/5dx9.pdb" "$datadir/5dx9.cif --cif"
+
 # need input files with multiple models
 assert_equal_total "$cli --separate-models -S -n 10" "$datadir/2jo4.pdb" "$datadir/2jo4.cif --cif"
 assert_equal_total "$cli --separate-models -S -n 10" "$datadir/2isk.pdb" "$datadir/2isk.cif --cif"
